import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { createClient } from '@supabase/supabase-js'

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)
  const tokenHash = searchParams.get('token_hash')

  if (!tokenHash) {
    return NextResponse.redirect(`${origin}/login`)
  }

  // Step 1: Verify the token using a standard (non-SSR) client with implicit
  // flow. The SSR client enforces PKCE, which is incompatible with tokens
  // generated by admin.generateLink. The implicit-flow client verifies
  // token_hash directly without needing a code_verifier.
  const implicitClient = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { auth: { flowType: 'implicit', detectSessionInUrl: false, persistSession: false } }
  )

  const { data, error } = await implicitClient.auth.verifyOtp({
    token_hash: tokenHash,
    type: 'recovery',
  })

  if (error || !data.session) {
    console.error('verify-reset error:', error?.message)
    return NextResponse.redirect(`${origin}/forgot-password?error=expired`)
  }

  // Step 2: Transfer the verified session into SSR cookies so the
  // reset-password page (and middleware) can read it.
  const response = NextResponse.redirect(`${origin}/reset-password`)

  const ssrClient = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return request.cookies.getAll() },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          )
        },
      },
    }
  )

  await ssrClient.auth.setSession({
    access_token: data.session.access_token,
    refresh_token: data.session.refresh_token,
  })

  return response
}
